# curl  --data 'info=aGVsbG8gYmFzZTY0' http://127.0.0.1:8188/decode
POST {{host}}/v1/decode
Content-Type: application/x-www-form-urlencoded

info=aGVsbG8gYmFzZTY0

> {%
client.test("t1", function() {
  client.assert(response.status === 200, "status no pass");
});
%}

###

