GET {{host}}/v1/random?salt


> {%
client.test("test without salt", function() {
  client.assert(response.status === 400, "status no pass");
});
%}

###

GET {{host}}/v1/random?salt=233

> {%
client.test("test with salt", function() {
  client.assert(response.status === 200, "status no pass");
  client.assert(response.body.length === 33, "body no pass");
});
%}


###
