---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by eric.
--- DateTime: 2021/4/19 8:34 下午
---
local json = require "cjson"

ngx.req.read_body()

local args = ngx.req.get_post_args()
if not args or not args.info then
    ngx.log(ngx.ERR,"l1")
    ngx.exit(ngx.HTTP_BAD_REQUEST)
end 

local ip = ngx.var.remote_addr
local ua = ngx.req.get_headers()['user-agent'] or ''
local info = ngx.decode_base64(args.info)

local resp = {}
resp.ip = ip
resp.ua = ua
resp.info = info

ngx.say(json.encode(resp))