---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by eric.
--- DateTime: 2021/7/5 7:40 下午
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by eric.
--- DateTime: 2021/6/9 5:32 下午
---
local args = ngx.req.get_uri_args()

if not args.key or (type(args.key) == "string" and #args.key == 0) then
    ngx.exit(ngx.HTTP_BAD_REQUEST)
end

local redis = require("lualib.redis_util")
local redis_opts = {
    host = '127.0.0.1',
    port = 6379,
    db_index = 0,
    password = nil,
    keepalive = 60000,
    pool_size = 200,
    connect_timeout = 3000,
    send_timeout = 200,
    read_timeout = 200
}

local red = redis:new(redis_opts)

local res, err = red:get(args.key)
if err then
    ngx.say("failed to get: ", err)
    return
end

-- ngx.say / ngx.print 可以直接返回 list（table不行），会自动拼接为一个字符串
local r_list = {
    "key: ",
    args.key,
    "  value: ",
    res
}
ngx.say(r_list)

-- 或者直接传多个
--ngx.say("key: ", args.key, "  value: ", res)

-- 最好不要进行 字符串拼接，对性能有影响
--ngx.say("key: " .. args.key .. "  value: " .. res)
