---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by eric.
--- DateTime: 2021/6/9 5:32 下午
---
local args = ngx.req.get_uri_args()

if not args.key or (type(args.key) == "string" and #args.key == 0) then
    ngx.exit(ngx.HTTP_BAD_REQUEST)
end

local redis = require "resty.redis"
local red = redis:new()

red:set_timeouts(1000, 1000, 1000) -- 1 sec

-- TODO host
local ok, err = red:connect("host.docker.internal", 6379)
if not ok then
    ngx.say("failed to connect: ", err)
    return
end

ok, err = red:set(args.key, args.value)
if not ok then
    ngx.say("failed to set: ", err)
    return
end

ngx.say("set result: ", ok)
