---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by eric.
--- DateTime: 2021/7/21 5:58 下午
---
local logger = require 'lualib.zlog_logger'
logger:init("/opt/winterfell/conf/zlog_nginx.conf")