---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by eric.
--- DateTime: 2021/5/28 5:37 下午
---

local _M = {}

function _M.is_number(...)
    local args = { ... }

    local num

    for _, v in ipairs(args) do
        num = tonumber(v)
        if nil == num then
            return false
        end
    end

    return true
end

function _M.response_msg(code_msg, data)
    local response_table = {}
    response_table.code = code_msg.code
    response_table.msg = code_msg.msg
    response_table.data = data
    return cjson.encode(response_table)
end

return _M