---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by eric.
--- DateTime: 2021/5/28 5:37 下午
---

local _M = {}

function _M.is_number(...)
    local args = { ... }

    local num

    for _, v in ipairs(args) do
        num = tonumber(v)
        if nil == num then
            return false
        end
    end

    return true
end

return _M