---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by eric.
--- DateTime: 2021/4/18 10:32 下午
---
local args = ngx.req.get_uri_args()

if not args.salt or (type(args.salt) == "string" and #args.salt == 0) then
    ngx.exit(400)
end 

local resp_string = ngx.md5(ngx.time() .. args.salt)
ngx.say(resp_string)