---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by eric.
--- DateTime: 2021/7/5 7:19 下午
---

local _M = {}

function _M.code_msg()
    local code_msg = {
        SUCC = { code = 0, msg = "success" },
        PARAM_ERROR = { code = 10001, msg = "request params error" },
        AUTH_ERROR = { code = 10002, msg = "auth failed" },
        REDIS_ERROR = { code = 10003, msg = "redis error" },
        SERVER_ERROR = { code = 10004, msg = "server error" }
    }
    return code_msg
end

function _M.redis_hget()
    local redis_hget = {
        redis_opts = {
            host = '127.0.0.1',
            port = 6379,
            pool_size = 512,
            read_timeout = 55
        },
        pd_file_path = "/opt/needle/proto/pb/gdt_rta.pb"
    }
    return redis_hget
end

return _M