---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by eric.
--- DateTime: 2021/4/19 8:34 下午
---
local json = require "cjson"

--TODO 提取为公共函数，get_args_post_or_uri()
local method = ngx.req.get_method()
local args
local err
if method == 'POST' then
    -- post body_data 需要先read
    ngx.req.read_body()
    args, err = ngx.req.get_post_args()
elseif method == 'GET' then
    args = ngx.req.get_uri_args()
else
    err = "bad request method"
end

if err then
    ngx.log(ngx.ERR, "failed to decode post args: ", err)
    ngx.exit(ngx.HTTP_BAD_REQUEST)
end
if not args then
    ngx.say("failed to get post args")
    return
end
if not args.info then
    ngx.say("failed to get post args: ", "args.info is nil")
    return
end

local ip = ngx.var.remote_addr
local ua = ngx.req.get_headers()['user-agent'] or ''
local info = ngx.decode_base64(args.info)

local resp = {}
resp.ip = ip
resp.ua = ua
resp.info = info

ngx.say(json.encode(resp))